gmuGADIG/Fruit-Punch

Assets/Scenes/Development Scenes/EnemySpawningTest.unity, Assets/Scenes/Development Scenes/EnemySpawningTest.unity.meta, Assets/Scripts/Characters/Enemy/EnemySpawns.cs, Assets/Scripts/Characters/Enemy/EnemySpawns.cs.meta, Assets/Scripts/Environment/CameraTrigger.cs, Assets/Scripts/Environment/CameraTrigger.cs.meta, Assets/Scripts/Misc/Utils.cs, ProjectSettings/SceneTemplateSettings.json
This creates the scripts (no prefabs) for the enemy spawner (incomplete since design still needs to discuss details) and a Camera Trigger, which has an event which fires once when the object is in the bounds of the camera.
=> Enemy spawner and Camera Trigger

Assets/Prefabs/Enemies/EnemyHealthBar.prefab, Assets/Prefabs/Enemies/EnemyHealthBar.prefab.meta, Assets/Scenes/Development Scenes/PauseMePlz.unity, Assets/Scripts/Characters/Enemy/EnemyHealthBar.cs, Assets/Scripts/Characters/Enemy/EnemyHealthBar.cs.meta
Prefab that Takes Max Health and current health and changes slider to match
Enemy Health Script isn't finished so placeholder values
=> Basic Enemy health Slider

Assets/Scripts/DamageType.cs, Assets/Scripts/DamageType.cs.meta, Assets/Scripts/Health.cs, Assets/Scripts/Health.cs.meta
Script Compatibility with Enemy and Player Health. Deals with maximums, currents, death instances and healing/damage. Christian added compatibility & health bar functionality, while Justin updated original health functions to events.
=> Health Program

Assets/Prefabs/PlayerHealthBar.prefab, Assets/Prefabs/PlayerHealthBar.prefab.meta, Assets/Scenes/Development Scenes/HealthBarUI.unity, Assets/Scenes/Development Scenes/HealthBarUI.unity.meta, Assets/Scripts/PlayerHealth.cs, Assets/Scripts/UI/GamePlayUI.meta, Assets/Scripts/UI/GamePlayUI/PlayerHealthBarUI.cs, Assets/Scripts/UI/GamePlayUI/PlayerHealthBarUI.cs.meta
PR here for comparison with https://github.com/gmuGADIG/Fruit-Punch/pull/36 
I think the other one is more complete and actually adds some things I wanted to do during the meeting, although I do have some opinions about their design.
We added a health bar using UI images, TextMeshPro, and exposed fields in playerHealth classes.
=> Basic Health Bar UI Completed

Assets/Prefabs/PlayerHealthBar.prefab, Assets/Scenes/Development Scenes/HealthBarUI.unity, Assets/Scripts/Characters/Health.cs, Assets/Scripts/UI/GamePlayUI/PlayerHealthBarUI.cs
I made it so that the health bar and text updates whenever the player takes damage. The player(Health component) will need to added to the health bar UI in order to work.
=> The health bar updates

Assets/Prefabs/Environment/Pickup.prefab, Assets/Scenes/Development Scenes/Pickup.unity, Assets/Scripts/Environment/HealthPickup.cs, Assets/Scripts/Environment/HealthPickup.cs.meta, Assets/Scripts/Environment/Pickup.cs
The Pickup script is now abstract and is inherited by the HealthPickup script. The HealthPickup script heals the players.
=> Made Pickup abstract and made HealthPickup script

Assets/Scenes/Development Scenes/EnemyAttack.unity, Assets/Scenes/Development Scenes/EnemyAttack.unity.meta, Assets/Scripts/Characters/Enemy/Enemy.cs
The melee damage is hard coded for now
=> Added melee damage

Packages/manifest.json, Packages/packages-lock.json
Imported AI Navigation from the package manager.
=> Imported NavMesh

Assets/Prefabs/UI/InGameCanvas.prefab, Assets/Scenes/Build Scenes/DemoLevel.unity, ProjectSettings/Packages/com.unity.probuilder/Settings.json
made them different colors also
=> did the text for player one and two score

Assets/Scenes/Build Scenes/CutsceneTest.unity
scenes need an object with the SwitchScene script attached to transition to the next scene correctly
=> changed CutsceneTest to properly transition to DemoLevel02

Assets/Scenes/Development Scenes/PlayerScoreTesting.unity, Assets/Scenes/Development Scenes/PlayerScoreTesting.unity.meta, Assets/Scripts/UI/GamePlayUI/PlayerScore.cs, Assets/Scripts/UI/GamePlayUI/PlayerScore.cs.meta, Assets/Scripts/UI/GamePlayUI/ScoreTestingScripts.meta, Assets/Scripts/UI/GamePlayUI/ScoreTestingScripts/AddScoreOnClick.cs, Assets/Scripts/UI/GamePlayUI/ScoreTestingScripts/AddScoreOnClick.cs.meta, Assets/Scripts/UI/GamePlayUI/ScoreTestingScripts/SubtractScoreOnClick.cs, Assets/Scripts/UI/GamePlayUI/ScoreTestingScripts/SubtractScoreOnClick.cs.meta, Assets/Scripts/UI/GamePlayUI/UpdateScoreRank.cs, Assets/Scripts/UI/GamePlayUI/UpdateScoreRank.cs.meta
#144 
Created PlayerScore script and UpdateScoreRank script
PlayerScore has variables playerScore (private int) and rankList(struct rankLevels {string rankName, int pointThreshold})
- public event Action updateScoreAndRank;
- functions: addScore(int), subtractScore(int), getScore() return int, and getRank() return string;
UpdateScoreRank is a rough example of using PlayerScore to change UI elements.
The Scene PlayerScoreTesting and scripts AddScoreOnClick and SubtractScoreOnClick were created to test the PlayerScore script.
=> Player score base

Assets/Scripts/Scene/GameSceneManager.cs
=> camera now works like SMB1

Assets/Scripts/Scene/GameSceneManager.cs
This makes combat encounters actually finish.
=> gameSceneManager subcribes to wave complete

Assets/Scripts/Characters/Enemy/EnemyBehaviors/Enemy.cs, Assets/Scripts/Characters/Grabbable.cs, Assets/Scripts/Characters/Player/Grabber.cs, Packages/manifest.json, Packages/packages-lock.json
* fix bug with grab indicator not working #222 
* fix bug with the player grabbing dead enemies #185 
* fixed by making thrown enemies only take damage when entering a state other than grabbed
* refactored grabber.cs to make it more readable
* refactored `Grabbable.InGrabbingRange` and `Grabbable.OutOfGrabbingRange` to take in a grabber parameter to avoid the disabled event handler from calling `OutOfGrabbingRange` after the grabber already left the grabbing range
=> fix grabbing bugs

Assets/Scenes/Build Scenes/Level 01/Level1-1.unity, Assets/Scenes/Build Scenes/Level 01/Level1-2.unity, Assets/Scenes/Build Scenes/Level 01/Level1-4.unity, Assets/Scenes/Build Scenes/Level 02/Level2-1.unity, Assets/Scenes/Build Scenes/Level 02/Level2-3.unity, Assets/Scenes/Build Scenes/Level 02/Level2-4.unity, Assets/Scripts/Characters/Boss/BossLeadingLady.cs, Assets/Scripts/Characters/Health.cs, Assets/Scripts/Environment/Spawner/EnemySpawns.cs, Assets/Scripts/Environment/Spawner/ScreenSpawner.cs, Assets/Scripts/Scene/GameSceneManager.cs, ProjectSettings/TagManager.asset
Level 2's stages (except 2-2, which didn't seem finished) have been integrated into the playable game. The enemy spawners are very basic and temporary, no hazards have been made yet, and level 2's boss doesn't exist yet.
=> Level2 integration

Assets/Prefabs/PlayerSelect/Character Selector prefab.prefab
Rescaled the Character Selector prefab to fit within the screen, while keeping the readability of the text
Fixes #238
=> Scaling Adjustments

Assets/Scenes/Build Scenes/OptionsMenu.unity, Assets/Scripts/UI/OptionsMenu.cs, Assets/Scripts/UI/OptionsMenu.cs.meta
Put down the framework for the options menu, matching the layout asked for by the UI document.
The sliders have values between 0 and 2, and default to 1 on start. The updating logic is in OptionsMenu.cs
OptionsBackButton.cs is deprecated
=> Options Menu Creation

Assets/Prefabs/Bosses/BaseBoss.prefab, Assets/Prefabs/Bosses/BaseBoss.prefab.meta, Assets/Prefabs/Bosses/LeadingLady.prefab, Assets/Scenes/Build Scenes/Level 01/Level1-4.unity, Assets/Scripts/Characters/Boss/Boss.cs, Assets/Scripts/Characters/Boss/BossLeadingLady.cs, Assets/Scripts/Characters/Grabbable.cs, Assets/Scripts/Characters/HurtBox.cs
Created a base boss prefab for bosses so that I don't have to see as much duplicated code as I already do. In addition to a base boss script, I also added the functionality to throw bosses. 
I do really wish we could refactor the enemies and bosses to not have duplicated code between the two but I'll leave that for the future.
=> 233 throwable bosses & BaseBoss prefab+script

Assets/Scripts/Characters/StayInCamera.cs
=> knockback no longer sends things offscreen

Assets/Scripts/Characters/Health.cs
=> fix knockback direction wrong
